---
    - name: Configure Prism
      hosts: localhost
      vars_files:
        - vars.yml
      tasks:
        - name: create ahv subnets
          include_tasks: ahv-subnet-playbook.yml
          with_items:
            - {net_name: "{{ network_name }}", net_vlan: "{{ network_vlan }}"}