---
nodes:
    - manual_mode:
      cvm_ip: "10.48.69.6"
      cvm_gb_ram: 32
      hypervisor_hostname: "superman1"
      ipmi_ip: "10.49.44.77"
      hypervisor: "kvm"
      hypervisor_ip: "10.48.69.2"
      node_position: "A"
    - manual_mode:
      cvm_ip: "10.48.69.7"
      cvm_gb_ram: 32
      hypervisor_hostname: "superman2"
      ipmi_ip: "10.49.44.78"
      hypervisor: "kvm"
      hypervisor_ip: "10.48.69.3"
      node_position: "B"
    - manual_mode:
      cvm_ip: "10.48.69.8"
      cvm_gb_ram: 32
      hypervisor_hostname: "superman3"
      ipmi_ip: "10.49.44.79"
      hypervisor: "kvm"
      hypervisor_ip: "10.48.69.4"
      node_position: "C"
    - manual_mode:
      cvm_ip: "10.48.69.9"
      cvm_gb_ram: 32
      hypervisor_hostname: "superman4"
      ipmi_ip: "10.49.44.80"
      hypervisor: "kvm"
      hypervisor_ip: "10.48.69.5"
      node_position: "D"